{% set name = "sphinx-remove-toctrees" %}
{% set version = "1.0.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4808d1edf151c06eff6d2c3922ec7ebc9fd3aa1762de1b2e1674a37f5ac9ce2d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - sphinx >=5

test:
  imports:
    - sphinx_remove_toctrees
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/executablebooks/sphinx-remove-toctrees
  summary: Reduce your documentation build size by selectively removing toctrees from pages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
